Repository helyne/drought_detection, pull requests merged in 2022-07, with the labels that each got.

#2 feature engineering branch
  drought_detection/feature_engineering.py
  drought_detection/feature_engineering_test
Labels: Preprocessing

#1 Preprocessing_2 branch
  drought_detection/hello_from_patricia
Labels: enhancement

#3 update makefile
  Makefile
  drought_detection/feature_engineering.py
  drought_detection/feature_engineering_test
  drought_detection/hello_from_patricia
Labels: documentation, cleanup code

#4 Added EDA notebook, and updated requirements.txt with tensorflow
  .vscode/configurationCache.log
  .vscode/dryrun.log
  .vscode/targets.log
  notebooks/chris_eda.ipynb
  requirements.txt
Labels: EDA - Exploratory Data Analysis

#11 adding save function to basic model and adapting requirements.txt
  drought_detection/train_basic_mdel.py
  requirements.txt
Labels: enhancement, CNN

#13 updated data_handling functions and added basic feature engineering n…
  drought_detection/data_handling.py
  notebooks/helyne_marie_feat_eng.ipynb
Labels: documentation, Preprocessing, cleanup code, EDA - Exploratory Data Analysis

#16 added gcp.py file and updated params.py file
  drought_detection/gcp.py
  drought_detection/params.py
Labels: enhancement, save model, parameters

#21 included BUCKET_TRAINING_FOLDER
  Makefile
Labels: enhancement, parameters
